# Generated by Django 5.2.17 on 2026-09-02 16:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import welfare.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Convention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="aggiornato il"),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="nome"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="attiva")),
            ],
            options={
                "verbose_name": "convenzione",
                "verbose_name_plural": "convenzioni",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WelfareProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="aggiornato il"),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="nome"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="data inizio"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="data fine"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="attivo")),
            ],
            options={
                "verbose_name": "programma welfare",
                "verbose_name_plural": "programmi welfare",
                "ordering": ["-active", "name"],
                "permissions": [
                    ("manage_welfare", "Può amministrare il welfare aziendale")
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="aggiornato il"),
                ),
                (
                    "employee_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="matricola",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="attivo")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "dipendente",
                "verbose_name_plural": "dipendenti",
                "ordering": ["user__last_name", "user__first_name", "user__username"],
            },
        ),
        migrations.CreateModel(
            name="VoucherAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_assigned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantità assegnata"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="assegnato il"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="aggiornato il"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assegnato da",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="welfare.employeeprofile",
                        verbose_name="dipendente",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aggiornato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "allocazione voucher",
                "verbose_name_plural": "allocazioni voucher",
                "ordering": ["voucher_type__convention__name", "voucher_type__name"],
            },
        ),
        migrations.CreateModel(
            name="VoucherRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantità",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "In attesa"),
                            ("APPROVED", "Approvata"),
                            ("REJECTED", "Rifiutata"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                        verbose_name="stato",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="richiesta il"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="elaborata il"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, verbose_name="motivazione del rifiuto"
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="welfare.voucherallocation",
                        verbose_name="allocazione",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests_processed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="elaborata da",
                    ),
                ),
            ],
            options={
                "verbose_name": "richiesta voucher",
                "verbose_name_plural": "richieste voucher",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="VoucherDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantità",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="consegnato il"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="note")),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="welfare.voucherallocation",
                        verbose_name="allocazione",
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries_registered",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="consegnato da",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery",
                        to="welfare.voucherrequest",
                        verbose_name="richiesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "consegna voucher",
                "verbose_name_plural": "consegne voucher",
                "ordering": ["-delivered_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=welfare.models.attachment_upload_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        max_length=255, verbose_name="nome file originale"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="caricato il"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="caricato da",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="welfare.voucherrequest",
                        verbose_name="richiesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "allegato",
                "verbose_name_plural": "allegati",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VoucherType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="aggiornato il"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descrizione"),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="valore unitario",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="attivo")),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voucher_types",
                        to="welfare.convention",
                        verbose_name="convenzione",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo voucher",
                "verbose_name_plural": "tipi voucher",
                "ordering": ["convention__name", "name", "unit_value"],
            },
        ),
        migrations.AddField(
            model_name="voucherallocation",
            name="voucher_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="welfare.vouchertype",
                verbose_name="tipo voucher",
            ),
        ),
        migrations.AddField(
            model_name="voucherallocation",
            name="welfare_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="welfare.welfareprogram",
                verbose_name="programma welfare",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="aggiornato il"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="importo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budgets_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budgets_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aggiornato da",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="welfare.employeeprofile",
                        verbose_name="dipendente",
                    ),
                ),
                (
                    "welfare_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="welfare.welfareprogram",
                        verbose_name="programma welfare",
                    ),
                ),
            ],
            options={
                "verbose_name": "budget dipendente",
                "verbose_name_plural": "budget dipendenti",
                "ordering": ["employee__user__last_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="voucherrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="request_quantity_at_least_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="voucherdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="delivery_quantity_at_least_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="vouchertype",
            constraint=models.UniqueConstraint(
                fields=("convention", "name", "unit_value"),
                name="uniq_vouchertype_convention_name_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="vouchertype",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_value__gt", 0)),
                name="vouchertype_unit_value_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="voucherallocation",
            constraint=models.UniqueConstraint(
                fields=("employee", "welfare_program", "voucher_type"),
                name="uniq_allocation_employee_program_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeebudget",
            constraint=models.UniqueConstraint(
                fields=("employee", "welfare_program"),
                name="uniq_budget_employee_program",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeebudget",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="budget_amount_not_negative",
            ),
        ),
    ]
